### ISSUE TITLE
生成屬性 Random no work

### ISSUE THREAD

**Issue by smaragdinesapphire** [wayne930242/coc7e#11]
環境:
Chrome
版本 80.0.3987.149 (正式版本) (64 位元)

問題:
點選 "生成屬性" 的 Dice Icon後，
Console 會顯示:
Uncaught ReferenceError: count is not defined
    at n (rpgbasic.js:4)

**Comment by smaragdinesapphire** [comment]
Note:
無論是 "1920s" 還是 "現代" 都有這問題。

**Comment by caasi** [comment]
在 7032642e60e54b9a633ef6406647becc4215d75f 修掉了這個問題，請再試試看。
